### ISSUE TITLE
`styled-import` errors out in `create-react-app`

### ISSUE THREAD

**Issue by ryaninvents** [glortho/styled-import#2]
I love the API design here and am really excited to use `styled-import`! However, I get a build error when I try to use it with `create-react-app`.

First it claims it cannot find the `css` module. If I install `css` myself, I then get the issue:

```
TypeError: styled-import/macro: Cannot read property 'some' of undefined Learn more: https://www.npmjs.com/package/styled-import
```

To reproduce the issue:

```bash
git clone https://gist.github.com/ryaninvents/b12791f724d2553f3ec6826090d2dbd2 styled-import-cra
cd styled-import-cra
npm install
npm start
```

**Comment by ryaninvents** [comment]
Also, I'd like to note that I enjoy working on macros, so if there's some way I can contribute to a fix then I'd be glad to help!

**Comment by glortho** [comment]
Sorry to hear this @ryaninvents ! Could it be that it's not installing dev dependencies in CRA? Are you able to get your install flow to add the `-D` flag, or otherwise ensure that `NODE_ENV=development`?

**Comment by ryaninvents** [comment]
`styled-import` is definitely installed, but `css` is not:

```
$ npm ls styled-import    
new@1.0.0 ~/demos/styled-import-cra
└── styled-import@0.3.0

$ npm ls css          
new@1.0.0 ~/demos/styled-import-cra
└── (empty)
```

I exported a CodeSandbox to create [my gist](https://gist.github.com/ryaninvents/b12791f724d2553f3ec6826090d2dbd2) so everything relevant to this discussion is added as a regular dependency anyways. Also, I tried `NODE_ENV=development` as well as `npm install --dev` with the same results.

It seems as though the `css` package should be a regular dependency, not a devDependency, since [devDependencies are never installed transitively](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies).

**Comment by glortho** [comment]
you’re right — I’m not sure why it’s not in regular deps. I’m traveling right now but if you want to make the change and pr it I’ll merge! thanks for your help Ryan!


________________________________

**Comment by ryaninvents** [comment]
Glad to help! By the way, I love what you've built here. Really nice implementation.

**Comment by glortho** [comment]
Thank you for the kind words Ryan! So glad you like it. :-)


________________________________

**Comment by glortho** [comment]
This should be fixed now -- let me know if you still have problems!
